title: NJUPT SAST
brand: NJUPT SAST
description: 南京邮电大学大学生科学技术协会官方网站
baseurl: "/info"
url: "https://njupt-sast-technology-center.github.io"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false

excerpt_separator: <!--more-->

about: "Igniting the Thought! <br /> 南京邮电大学大学生科学技术协会（简称 SAST）是在校团委指导下，独立开展活动的学生科技文化及学术研究的组织。"
